name: advanced CI
on:
  push:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Docker Image
          run: docker build -t myapp .
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Testing..." 
