name: advanced CI
on:
  push:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Step
          run: echo "Building..."
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Testing..." 
